title:            tupleblog
description:      บล็อกภาษาไทยที่อยากเขียนอะไรก็เขียน
disqus_shortname: tupleblog
reading_time:     true
words_per_minute: 800
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
# url: # comment this when pushing to server
url: https://tupleblog.github.io # comment this when testing locally

# Owner/author information
owner:
  name: tupleblog
  avatar: tpbloglogo.png
  bio: "บล็อกภาษาไทยที่อยากเขียนอะไรก็เขียน"
  email: tupleblog@outlook.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github: tupleblog
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-62561922-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Bangkok
future:      true
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# workaround for ssl error due to jekyll-gist
# see https://github.com/jekyll/jekyll/issues/5037
gist:
  noscript: false

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 12

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..4
  enable_coderay: false

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
